# Generated by Django 4.0.4 on 2022-04-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='tokken_type',
            new_name='token_type',
        ),
    ]
